# Generated by Django 2.1.5 on 2019-02-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32, unique=True)),
                ('hex_color', models.CharField(default='#ffffff', max_length=12)),
            ],
            options={
                'verbose_name': 'Test Status',
            },
        ),
    ]
