# Generated by Django 2.1.5 on 2019-02-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(default='No description provided...', max_length=64)),
            ],
            options={
                'verbose_name': 'Test Category',
            },
        ),
    ]
