# Generated by Django 2.1.5 on 2019-02-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0003_auto_20190204_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubcategory',
            name='subcategory',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='testsubcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='testsubcategory',
            name='category',
        ),
    ]
