# Generated by Django 2.1.5 on 2019-02-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0004_auto_20190204_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name': 'Test Category', 'verbose_name_plural': 'Test Categories'},
        ),
        migrations.AlterModelOptions(
            name='teststatus',
            options={'verbose_name': 'Test Status', 'verbose_name_plural': 'Test Status'},
        ),
        migrations.AlterModelOptions(
            name='testsubcategory',
            options={'verbose_name': 'Test Subcategory', 'verbose_name_plural': 'Test Subcategories'},
        ),
    ]
