# Generated by Django 2.1.5 on 2019-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0005_auto_20190204_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatus',
            name='text_hex_color',
            field=models.CharField(default='#000000', max_length=12),
        ),
    ]
